name: ci
run-name: Build & Push New Docker Image
on: [
    push,
    workflow_dispatch
]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [3.6, 3.8]
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                logout: true
            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
                logout: true
            - name: Build and Push to DockerHub & Github Container Registry (ghcr.io)
              uses: docker/build-push-action@v4
              with:
                context: .
                file: Dockerfile.python
                push: true
                build-args:
                  PYTHON_VERSION=${{ matrix.python-version }}
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ matrix.python-version }}-ihr
                  ghcr.io/0xmostafa/python:${{ matrix.python-version }}-ihr
