name: ci
run-name: Build & Push New Docker Image
on: [push]

jobs:
    push-and-push-to-dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                logout: true
            - name: Login to ghcr.io
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
                logout: true
            - name: Build and Push to DockerHub
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile.base-python
                push: true
                tags: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/python:latest
                    ghcr.io/0xmostafa/python:latest