name: ci
run-name: Build & Push New Docker Image
on: [
    push,
    workflow_dispatch
]

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                logout: true
            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
                logout: true
            - name: Image Metadata
              id: metadata
              uses: docker/metadata-action@v4
              with:
                images:
                    0xmstfa/python
            - name: Build and Push to DockerHub & Github Container Registry (ghcr.io)
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile.python
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}