name: GH Action Demo
run-name: ${{ github.actor }} is testing gh actions
on: [push]

jobs:
  demo-gh-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by ${{ github.event_name }}"
      - run: echo "executing on ${{ runner.os }}"
      - run: echo "branch ${{ github.ref }}"
      - run: echo "repo name is ${{ github.repository }}"
      - name: checkout code
        uses: actions/checkout@v3
      - name: list files in repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "job status is ${{ job.status }}"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "second job ${{ job }}"
